<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <!--responcive-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--fontawesom-->
    <script src="https://kit.fontawesome.com/3903820350.js" crossorigin="anonymous"></script>
    <!--favicon-->
    <link rel="icon" type="image/png" href="img/title.png" />
    <!--slider-->
    <link rel="stylesheet" type="text/css" href="slider/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slider/slick/slick-theme.css"/>
    <!--css-->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <p>Livreson offerte à partir de 65€ d'achat !</p>
        <img class="promo" src="img/ribbon.svg" alt="promotion">
        <div class="container">
            <a class="logo"href="index.html"><img src="img/logo.png" alt="logo"></a>
            <div class="none">
                <span class="panier">Mon panier</span>
                <span class="fixed"><i class="fas fa-shopping-cart"></i>42,00€</span>
            </div>
            <nav>
                <a href="listingproduct.php">Thés</a>
                <a href="#">Grands crus</a>
                <a href="#">Accessoires</a>
                <a href="#">Epicerie</a>
                <a href="about.html">Notre histoire</a>
            </nav>
        </div>
    </header>
    <!--*********************************************************************************************************-->
    <main class="container">
        <section class="noir">
            <h1>Notre carte de thés</h1>
            <artictle class='description'>
                <h2 class="titre">Thé Noir<span></span></h2>
                <p>Le thé noir, que les chinois appellent thé rouge en référence à la couleur cuivrée de son infusion, est un thé complètement oxydé. La fabrication du thé noir, se fait en cinq étapes : le fleurissage, le roulage, l'oxydation, la torréfaction et le triage. Cette dernière opération permet de différencier les différents grades.</p>
            </artictle>
            <article>
                <h3 class="listing">Blue of London</h3>
                <img src="img/product/product3.jpg" alt="Blue of London">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">9,00€</p>
                    <a class="boutton" href="product.php?id=0">voir ce produit</a>
                </figure>
            </article>
            <article>
                <h3 class="listing">Thé des Lords</h3>
                <img src="img/product/product6_big.jpg" alt="Thé des Lords">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">8,20€</p>
                    <a class="boutton" href="product.php?id=1">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Thé des Vahinés</h3>
                <img src="img/product/product3.jpg" alt="Thé des Vahinés">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">9,40€</p>
                    <a class="boutton" href="product.php?id=2">voir ce produit</a>
                </figure>    
            </article>
        </section>
         <section class="vert">
            <artictle class='description'>
                <h2 class="titre">Thé vert<span></span></h2>
                <p>Réputé pour ses nombreuses vertus grâce à sa richesse en antioxydants, le thé vert désaltère, tonifie, apaise, fortifie et procure une incontestable sensation de bien-être. Délicat et peu amer, il est apprécié à tout moment de la journée et propose une palette d'arômes très variés : végétal, minéral, floral, fruité.</p>
            </artictle>
            <article>
                <h3 class="listing">Thé du hammam</h3>
                <img src="img/product/product1.jpg" alt="Thé du hammam">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">8,40€</p>
                    <a class="boutton" href="product.php?id=3">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Vive le Thé!</h3>
                <img src="img/product/product4_big.jpg" alt="Vive le Thé">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">6,80€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>
                </article>
            <article>
                <h3 class="listing">Thé des Alizés</h3>
                <img src="img/product/product5_big.jpg" alt="Thé des Alizés">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">9,30€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
        </section>
         <section class="Oolong">
            <artictle class='description'>
                <h2 class="titre">Thé Oolong<span></span></h2>
                <p>Les Oolong, que les chinois appellent thé bleu-vert en référence à la couleur de leurs feuilles infusées, sont des thés semi-oxydés : leur oxydation n'a pas été menée à son terme. Spécialités de Chine et de Taïwan, il en existe une grande variété, en fonction de la région de culture, de l'espèce du théier ou encore du processus de fabrication. </p>
            </artictle>
            <article>
                <h3 class="listing">Vive les fêtes</h3>
                <img src="img/product/product8_big.jpg" alt="Vive les fêtes">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">11,10€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Fleur d'orangér Oolong</h3>
                <img src="img/product/product9_big.jpg" alt="Fleur d'orangér Oolong">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">10,90€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Oolong 7 agrumes</h3>
                <img src="img/product/product10_big.jpg" alt="Oolong 7 agrumes">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">13,20€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
        </section>
        <section class="blanc">
            <artictle class='description'>
                <h2 class="titre">Thé blanc<span></span></h2>
                <p>Le thé blanc est une spécialité de la province du Fujian. De toutes les familles de thé, c'est celle dont la feuille est la moins transformée par rapport à son état naturel. Non oxydé, le thé blanc ne subit que deux opérations : un flétrissage et une dessication. Il existe deux grands types de thés blancs : les Aiguilles d'Argent et les Bai Mu Dan. </p>
            </artictle>
            <article>
                <h3 class="listing">Thé des songes blancs</h3>
                <img src="img/product/product11_big.jpg" alt="Thé des songes blancs">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">12,00€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Bai mu dan</h3>
                <img src="img/product/product12_big.jpg" alt="Bai mu dan">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">9,50€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>
            </article>
            <article>
                <h3 class="listing">Aiguilles d'Aregnt</h3>
                <img src="img/product/product13_big.jpg" alt="Aiguilles d'Aregnt">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">47,20€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
        </section>
        <section class="Rooibos">
            <artictle class='description'>
                <h2 class="titre">Rooibos<span></span></h2>
                <p>Le Rooibos (appelé thé rouge bien qu'il ne s'agisse pas de thé) est une plante poussant uniquement en Afrique du Sud et qui ne contient pas du tout de théine. Son infusion donne une boisson très agréable, ronde et légèrement sucrée. Riche en antioxydants, faible en tanins et dénué de théine, le Rooibos peut être dégusté en journée comme en soirée. </p>
            </artictle>
            <article>
                <h3 class="listing">Rooibos à la verveine</h3>
                <img src="img/product/product14_big.jpg" alt="Rooibos à la verveine">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">7,00€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Spicy Passion</h3>
                <img src="img/product/product15_big.jpg" alt="Spicy Passion">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">9,00€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
            <article>
                <h3 class="listing">Rooibos des amants</h3>
                <img src="img/product/product16_big.jpg" alt="Rooibos des amants">
                <figure>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, doloribus, cumque recusandae ad laudantium autem explicabo quam iusto quasi in temporibus sit eum nesciunt accusamus minima suscipit blanditiis possimus quisquam libero dolorem!</p>
                    <p>A partir de</p>
                    <p class="prix">8,20€</p>
                    <a class="boutton" href="#">voir ce produit</a>
                </figure>    
            </article>
        </section>
    </main>
    <!--*********************************************************************************************************-->
    <footer>
        <div class="container">
            <div class="flexf">
                <p><i class="fas fa-lock"></i>paiment sécurisé</p>
                <p><i class="fas fa-truck"></i>livraison offerte</p>
                <p><i class="fas fa-money-bill-alt"></i>carte fidélité</p>
                <p><i class="fas fa-phone"></i>service client</p>
                <p><i class="fas fa-check-circle"></i>garantie qualité</p>
            </div>
            <nav>
                <div>
                    <strong>cup of tea</strong>
                    <ul>
                        <li><a href="#">Notre histoir</a></li>
                        <li><a href="#">Nos boutiques</a></li>
                        <li><a href="#">Le té de A à Z</a></li>
                        <li><a href="#">Espace Clients Professionels</a></li>
                        <li><a href="#">Recrutement</a></li>
                        <li><a href="#">Contactez-nous!</a></li>
                        <li><a href="#">L'École du thé</a></li>
                    </ul>
                </div>
                <div>
                    <strong>commande en ligne</strong>
                    <ul>
                        <li><a href="#">Premiere visite</a></li>
                        <li><a href="#">Aide FAQ</a></li>
                        <li><a href="#">Service client</a></li>
                        <li><a href="#">suivre ma comande</a></li>
                        <li><a href="#">Condition generales de vente</a></li>
                        <li><a href="#">Information légale</a></li>
                    </ul>
                </div>
                <div>
                    <strong>suivez-nous</strong>
                    <ul>
                        <li><a href="#">Npter Histoire</a></li>
                        <li><a href="#">Nos boutique</a></li>
                        <li><a href="#">le Thé de A à Z</a></li>
                        <li><a href="#">Espace Clients Professionels</a></li>
                    </ul>
                </div>
            </nav>
            <div class="troiswa">
                <img src="img/logo-3wa.png" alt="logo 3wa">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam dolor tempore a autem rem dolore porro iure eveniet laborum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde, commodi? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, harum, hic! Vero, velit reprehenderit quam cum quibusdam dolores odio cupiditate! Lorem ipsum dolor sit amet.</p>
            </div>
        </div>
    </footer>        
</body>
</html>